server:
  port: 9000
  address: 127.0.0.2

postgres:
  port: 5432
spring:
  datasource:
    url: jdbc:postgresql://localhost:${postgres.port}/users
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: MainPool
      minimum-idle: 3
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      initialization-fail-timeout: 90000
      auto-commit: false
      transaction-isolation: 2 #TRANSACTION_READ_COMMITTED
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  websecurity:
    debug: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://127.0.0.2:9000
        client:
          articles-client:
            registration:
              client-id: articles-client
              client-secret: "{noop}secret"
              client-name: Articles Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/articles-client-oidc
                - http://localhost:8080/authorized
              scopes:
                - openid
                - articles.read
                - profile
                - email
                - admin