server:
  port: ${PORT:8081}

postgres:
  port: 5432

spring:
  profiles:
    active: noSecurity
  datasource:
    url: jdbc:postgresql://localhost:${postgres.port}/comments
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: MainPool
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      initialization-fail-timeout: 90000
      auto-commit: false
      transaction-isolation: 2 #TRANSACTION_READ_COMMITTED
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      location: ${user.dir}/upload
