server:
  port: ${PORT:8080}

#logging:
#  level:
#    org.atmosphere=warn
vaadin:
  frontend:
    hotdeploy: false
  allowed-packages: com.vaadin,org.vaadin,com.example.application
# Launch the default browser when starting the application in development mode
  launch-browser: false
  #vaadin.compatibilityMode=true
  # PostgreSQL configuration.
postgres:
  port: 5432

spring:
#  profiles:
#    active: prod



  datasource:
    url: jdbc:postgresql://localhost:${postgres.port}/news-site
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MainPool
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      initialization-fail-timeout: 90000
      auto-commit: false
      transaction-isolation: 2 #TRANSACTION_READ_COMMITTED
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    properties:
      jakarta:
        persistence:
          validation:
            mode=none:
      hibernate:
        ddl-auto: update
        format_sql: true


  #spring.flyway.baseline-on-migrate=false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      location: ${user.dir}/upload
